import { describe, expect, it } from 'vitest';
import { reportMarkdown, reportName } from './vaultHealth';
import { DEFAULT_LINT, lintVault, type LintNote } from '../../shared/lint/vaultLint';

const NOW = Date.UTC(2026, 9, 7);
const DAY = 86_400_000;
const note = (name: string, over: Partial<LintNote> = {}): LintNote => ({ name, links: [], headings: [], aliases: [], fields: {}, text: `Text of ${name} with a few words in it, enough to be a note.`, mtimeMs: NOW - DAY, parsed: true, ...over });
const report = (notes: LintNote[]) => lintVault(notes, { ...DEFAULT_LINT, now: NOW });

describe('reportName', () => {
  it('is in reports/, named for the day', () => {
    expect(reportName(new Date(2026, 9, 7))).toBe('reports/Vault health 2026-10-07.md');
    expect(reportName(new Date(2026, 0, 3))).toBe('reports/Vault health 2026-01-03.md');
  });
});

describe('reportMarkdown', () => {
  const r = report([
    note('Hub.md', { links: [{ target: 'Quartely Report' }, { target: 'Gone' }, { target: 'Plan', heading: 'Nope' }] }),
    note('Quarterly Report.md', { links: [{ target: 'Hub' }] }),
    note('Work/Plan.md', { headings: ['Goals'], links: [{ target: 'Hub' }] }),
    note('Alone.md'),
    note('Old.md', { mtimeMs: NOW - 500 * DAY, links: [{ target: 'Hub' }] }),
  ]);
  const md = reportMarkdown(r, 'en', new Date(2026, 9, 7));

  it('opens with the day and what was checked', () => {
    expect(md.startsWith('# Vault health 2026-10-07\n')).toBe(true);
    expect(md).toContain('5 notes checked, 5 things to look at.');
  });

  it('lists each kind with its count, the notes as links that open them', () => {
    expect(md).toContain('## Broken links (2)');
    expect(md).toContain('- [[Hub]] links to Quartely Report (Did you mean [[Quarterly Report]]?)');
    expect(md).toContain('## Links to a missing heading (1)');
    expect(md).toContain('- [[Hub]] links to [[Work/Plan]] › Nope');
    expect(md).toContain('## Isolated notes (1)');
    expect(md).toContain('- [[Alone]]');
    expect(md).toContain('- [[Old]] (500 days ago)');
  });

  it('writes a name that does not exist as plain text: the report must not add links to nothing', () => {
    expect(md).toContain('links to Gone\n');
    expect(md).not.toContain('[[Gone]]');
    expect(md).not.toContain('[[Quartely Report]]');
  });

  it('leaves out the kinds with nothing in them, and says when all is well', () => {
    expect(md).not.toContain('Identical notes');
    const clean = reportMarkdown(report([note('A.md', { links: [{ target: 'B' }] }), note('B.md', { links: [{ target: 'A' }] })]), 'en', new Date(2026, 9, 7));
    expect(clean).toContain('Nothing to report');
    expect(clean).not.toContain('##');
  });

  it('is written in the language of the app, and says it is generated', () => {
    expect(reportMarkdown(r, 'it', new Date(2026, 9, 7))).toContain('## Link rotti (2)');
    expect(md).toContain('*Generated by Vault health.');
  });

  it('the report, once it is a note in the vault, is not part of the next check', () => {
    const again = report([...[
      note('Hub.md', { links: [{ target: 'Alone' }] }), note('Alone.md'),
    ], note('reports/Vault health 2026-10-07.md', { text: md, links: [{ target: 'Alone' }, { target: 'Gone' }], mtimeMs: NOW - 900 * DAY })]);
    expect(again.findings.filter(f => f.kind === 'broken-link')).toEqual([]);
    expect(again.notes).toBe(3);
  });

  it('mentions the notes too large to be read', () => {
    const big = lintVault([note('A.md'), note('Big.md', { parsed: false, text: '' })], { ...DEFAULT_LINT, now: NOW });
    expect(reportMarkdown(big, 'en', new Date(2026, 9, 7))).toContain('1 note(s) are too large to be read');
  });
});
