// Runs the golden corpus through every pipeline and writes REPORT.md.
//
//   exact     output is byte-identical to the golden snippet
//   stable    a second pass changes nothing (parse(serialize(x)) serializes to the same text):
//             what makes diffs quiet after the first save
//   meaning   the output parses to the same mdast as the input (differences are cosmetic)
//   lost      for `ext` snippets: the construct's text did not survive at all

import fs from 'node:fs';
import { CORPUS } from './corpus.mjs';
import { PIPELINES as BASE, meaning } from './pipelines.mjs';
import { pmMarkdown } from './pm-markdown.mjs';

const PIPELINES = [...BASE, pmMarkdown];

// Block-joining artifacts (a leading/trailing blank line around tables, images, callouts) are
// removed by one line of post-processing in a real pipeline; they are not counted as damage.
const trimBlank = (s) => s.replace(/^\n+/, '').replace(/\n+$/, '');

// Obsidian constructs that must come back verbatim for a snippet to count as preserved.
const CONSTRUCTS = [/!?\[\[[^\]]+\]\]/g, /==[^=\n]+==/g, /\$\$[\s\S]+?\$\$|\$[^$\n]+\$/g, /^> \[![^\]]+\][+-]?[^\n]*/gm, /%%[^%]+%%/g, /(?<![\w/])#[A-Za-z][\w/-]*/g];
const constructsOf = (md) => CONSTRUCTS.flatMap((re) => md.match(re) ?? []);

const cap = (s, n = 400) => (s.length > n ? s.slice(0, n) + '…' : s);
const vis = (s) => JSON.stringify(s);

function diff(a, b) {
  const x = a.split('\n'), y = b.split('\n');
  const out = [];
  const n = Math.max(x.length, y.length);
  for (let i = 0; i < n; i++) {
    if (x[i] === y[i]) { out.push(`  ${x[i] ?? ''}`); continue; }
    if (x[i] !== undefined) out.push(`- ${x[i]}`);
    if (y[i] !== undefined) out.push(`+ ${y[i]}`);
  }
  return out.join('\n');
}

const results = {};
for (const p of PIPELINES) {
  results[p.name] = [];
  for (const c of CORPUS) {
    const golden = trimBlank(c.md);
    let out, again, error = null;
    try {
      out = trimBlank(p.roundTrip(c.md));
      again = trimBlank(p.roundTrip(out));
    } catch (e) { error = String(e && e.message || e); out = ''; again = ''; }
    let sameMeaning = false;
    try { sameMeaning = !error && meaning(out) === meaning(golden); } catch { /* unparsable output */ }
    results[p.name].push({
      id: c.id, cat: c.cat, ext: !!c.ext, golden, out, error,
      exact: !error && out === golden,
      stable: !error && out === again,
      meaning: sameMeaning,
      kept: !error && constructsOf(golden).every((k) => out.includes(k)),
    });
  }
}

const pct = (n, d) => `${n}/${d}`;
const lines = [];
lines.push('# Markdown round-trip spike: report', '');
lines.push(`Generated by \`npm run spike\` over ${CORPUS.length} golden snippets (${CORPUS.filter((c) => c.ext).length} are Obsidian-style extensions).`, '');
lines.push('| Pipeline | exact | stable after 1 pass | same meaning | extensions kept | errors |', '| --- | --- | --- | --- | --- | --- |');
for (const p of PIPELINES) {
  const r = results[p.name];
  lines.push(`| ${p.name} | ${pct(r.filter((x) => x.exact).length, r.length)} | ${pct(r.filter((x) => x.stable).length, r.length)} | ${pct(r.filter((x) => x.meaning).length, r.length)} | ${pct(r.filter((x) => x.kept && constructsOf(x.golden).length).length, r.filter((x) => constructsOf(x.golden).length).length)} | ${r.filter((x) => x.error).length} |`);
}
lines.push('', '## By category (exact / total)', '');
const cats = [...new Set(CORPUS.map((c) => c.cat))];
lines.push(`| Pipeline | ${cats.join(' | ')} |`, `| --- | ${cats.map(() => '---').join(' | ')} |`);
for (const p of PIPELINES) {
  const r = results[p.name];
  lines.push(`| ${p.name} | ${cats.map((k) => pct(r.filter((x) => x.cat === k && x.exact).length, r.filter((x) => x.cat === k).length)).join(' | ')} |`);
}

for (const p of PIPELINES) {
  const bad = results[p.name].filter((x) => !x.exact);
  lines.push('', `## ${p.name}: ${bad.length} snippet(s) not byte-identical`, '');
  for (const x of bad) {
    const tag = x.error ? `ERROR ${x.error}` : `${x.stable ? 'stable' : 'UNSTABLE'}, ${x.meaning ? 'same meaning' : 'MEANING CHANGED'}`;
    lines.push(`### ${x.id} (${x.cat}${x.ext ? ', ext' : ''}) — ${tag}`, '', '```diff', cap(diff(x.golden, x.out)), '```', '');
  }
}
fs.writeFileSync(new URL('./REPORT.md', import.meta.url), lines.join('\n') + '\n');
fs.writeFileSync(new URL('./results.json', import.meta.url), JSON.stringify(results, null, 1));

for (const p of PIPELINES) {
  const r = results[p.name];
  const withExt = r.filter((x) => constructsOf(x.golden).length);
  console.log(`${p.name.padEnd(14)} ext kept ${pct(withExt.filter((x) => x.kept).length, withExt.length)}  exact ${pct(r.filter((x) => x.exact).length, r.length)}  stable ${pct(r.filter((x) => x.stable).length, r.length)}  meaning ${pct(r.filter((x) => x.meaning).length, r.length)}  errors ${r.filter((x) => x.error).length}`);
}
