// Golden corpus for the Markdown codec (ADR 0001, #59).
//
// Each case is [group, id, markdown, expected?]. `markdown` is what a person or Obsidian would write;
// the codec must write back `expected` (default: the same text) and must then be stable: a second pass changes
// nothing. A case with an `expected` that differs is a *normalisation*: a deliberate, listed rewrite that
// never changes what a reader sees (see docs/contributing/adr/0001-markdown-canonical-format.md).
//
// Groups: inline, block, list, table, ext (Obsidian-style syntax), doc (frontmatter, whitespace, empty).

export type GoldenCase = readonly [group: string, id: string, markdown: string, expected?: string];

const L = (...lines: string[]): string => lines.join('\n');

export const GOLDEN: readonly GoldenCase[] = [
  // ── from the spike (64) ────────────────────────────────────────────────────
  ["inline", "para-1", "A plain paragraph with some words."],
  ["inline", "para-2", "First paragraph.\n\nSecond paragraph."],
  ["inline", "emphasis", "Some *italic*, some **bold**, and some ***both***."],
  ["inline", "strike", "This is ~~gone~~ now."],
  ["inline", "code-inline", "Run `npm test` before pushing."],
  ["inline", "code-inline-tick", "Use ``a `tick` inside`` code.", "Use `` a `tick` inside `` code."],
  ["inline", "link", "See [the docs](https://example.com/docs) for more."],
  ["inline", "link-title", "A [titled link](https://example.com \"Example site\")."],
  ["inline", "autolink", "Visit <https://example.com> today."],
  ["inline", "image", "![A diagram](attachments/0123456789abcdef0123456789abcdef.png)"],
  ["inline", "image-title", "![Alt text](img/a.png \"Caption\")"],
  ["inline", "hard-break", "Line one\\\nLine two"],
  ["inline", "escape", "Not a list: 1986\\. A good year, and \\*not italic\\*.", "Not a list: 1986. A good year, and \\*not italic\\*."],
  ["inline", "entities", "Fish &amp; chips &copy; 2026", "Fish & chips © 2026"],
  ["inline", "unicode", "Caffè, 日本語, emoji 🚀 and ligatures: ﬁ."],
  ["inline", "long-line", "This is one very long line that a naive serializer might be tempted to reflow at eighty columns, but it must stay exactly as the author wrote it, on a single line, forever."],
  ["inline", "inline-html", "Press <kbd>Ctrl</kbd> + <kbd>C</kbd> to copy."],
  ["block", "headings", "# H1\n\n## H2\n\n### H3\n\n#### H4\n\n##### H5\n\n###### H6"],
  ["block", "quote", "> A quote\n> over two lines."],
  ["block", "quote-nested", "> Outer\n>\n> > Inner"],
  ["block", "rule", "Above\n\n---\n\nBelow"],
  ["block", "code-fence", "```js\nconst a = 1;\nconsole.log(a);\n```"],
  ["block", "code-fence-nolang", "```\nplain text\n```"],
  ["block", "code-fence-md", "````md\n```js\nnested fence\n```\n````"],
  ["block", "code-indented", "Before\n\n    indented code\n    block\n\nAfter", "Before\n\n```\nindented code\nblock\n```\n\nAfter"],
  ["block", "html-block", "<div class=\"note\">\n  <p>Raw HTML block</p>\n</div>"],
  ["block", "details", "<details>\n<summary>More</summary>\n\nHidden *text*.\n\n</details>"],
  ["block", "footnote", "A claim.[^1]\n\n[^1]: The source."],
  ["block", "ref-link", "See [the spec][cm].\n\n[cm]: https://spec.commonmark.org/ \"CommonMark\"", "See [the spec](https://spec.commonmark.org/ \"CommonMark\").\n\n[cm]: https://spec.commonmark.org/ \"CommonMark\""],
  ["list", "list-bullets", "- one\n- two\n- three"],
  ["list", "list-ordered", "1. one\n2. two\n3. three"],
  ["list", "list-ordered-start", "3. three\n4. four"],
  ["list", "list-nested", "- a\n  - b\n    - c\n- d"],
  ["list", "list-mixed", "1. first\n   - sub bullet\n   - another\n2. second"],
  ["list", "list-loose", "- one\n\n- two\n\n- three"],
  ["list", "list-code", "- step\n\n  ```sh\n  make build\n  ```\n\n- next"],
  ["list", "tasks", "- [ ] todo\n- [x] done\n- [ ] later"],
  ["list", "tasks-nested", "- [ ] parent\n  - [x] child\n  - [ ] other child"],
  ["table", "table", "| Name | Qty |\n| --- | --- |\n| Apple | 3 |\n| Pear | 12 |"],
  ["table", "table-align", "| L | C | R |\n| :--- | :---: | ---: |\n| a | b | c |"],
  ["table", "table-inline", "| Item | Note |\n| --- | --- |\n| **bold** | `code` and [link](https://x.io) |"],
  ["table", "table-pipe", "| Expr | Meaning |\n| --- | --- |\n| a \\| b | either |"],
  ["ext", "wikilink", "Linked to [[Project plan]] here."],
  ["ext", "wikilink-alias", "See [[Project plan|the plan]] for details."],
  ["ext", "wikilink-heading", "Jump to [[Project plan#Milestones]]."],
  ["ext", "wikilink-block", "As noted in [[Meeting#^decision-1]]."],
  ["ext", "wikilink-path", "In [[Projects/Alpha/Plan]] we say so."],
  ["ext", "wikilink-in-list", "- [[One]]\n- [[Two|second]]\n- plain"],
  ["ext", "wikilink-in-code", "Literal `[[not a link]]` stays code."],
  ["ext", "embed-note", "![[Reusable snippet]]"],
  ["ext", "embed-image", "![[diagram.png|400]]"],
  ["ext", "highlight", "Some ==highlighted text== in a line."],
  ["ext", "math-inline", "Euler: $e^{i\\pi} + 1 = 0$ is neat."],
  ["ext", "math-block", "$$\n\\int_0^1 x^2\\,dx = \\tfrac{1}{3}\n$$"],
  ["ext", "callout", "> [!note]\n> A callout body."],
  ["ext", "callout-title", "> [!warning] Careful\n> Body of the warning\n> on two lines."],
  ["ext", "callout-fold", "> [!tip]- Folded by default\n> Hidden until opened."],
  ["ext", "tag-inline", "Filed under #project/alpha and #idea."],
  ["ext", "comment", "Visible %%hidden comment%% visible."],
  ["doc", "frontmatter", "---\ntitle: Plan\ntags: [a, b]\nstatus: draft\n---\n\n# Plan\n\nBody."],
  ["doc", "frontmatter-odd", "---\n# a comment the user wrote\nkey:   spaced   value\nlist:\n  - x\n  - y\nunknown_key: \"keep me\"\n---\n\nText."],
  ["doc", "empty", ""],
  ["doc", "only-title", "# Just a title"],
  ["doc", "trailing-nl", "Ends with one newline."],

  // ── inline, more ───────────────────────────────────────────────────────────
  ['inline', 'em-underscore', '_italic_ and __bold__', '*italic* and **bold**'],
  ['inline', 'em-nested', 'Some *italic with **bold** inside* text.'],
  ['inline', 'strong-nested', 'Some **bold with *italic* inside** text.'],
  ['inline', 'strike-nested', 'This ~~struck *and slanted*~~ text.'],
  ['inline', 'code-star', 'Use `a * b` as written.'],
  ['inline', 'code-pipe', 'Pipe `a | b` in code.'],
  ['inline', 'code-spaces', 'Spaces ` keep ` inside.', 'Spaces `keep` inside.'],
  ['inline', 'link-angle-url', 'Go to [there](<https://example.com/a b>).', 'Go to [there](https://example.com/a%20b).'],
  ['inline', 'link-parens', 'See [it](https://x.io/a_\\(b\\)).'],
  ['inline', 'link-email', 'Mail <me@example.com> now.', 'Mail [me@example.com](mailto:me@example.com) now.'],
  ['inline', 'link-bold', 'A [**bold link**](https://x.io) here.'],
  ['inline', 'link-in-em', 'Some *[linked](https://x.io) italic* text.', 'Some [*linked*](https://x.io) *italic* text.'],
  ['inline', 'image-empty-alt', '![](attachments/a.png)'],
  ['inline', 'image-in-text', 'Look ![inline](a.png) here.'],
  ['inline', 'image-linked', '[![badge](b.svg)](https://ci.example.com)'],
  ['inline', 'bare-url', 'Visit https://example.com/path?q=1 for more.'],
  ['inline', 'esc-hash', 'Not a heading: \\# text', 'Not a heading: # text'],
  ['inline', 'esc-brackets', 'Literal \\[brackets\\] here.'],
  ['inline', 'esc-backslash', 'A backslash \\\\ in text.'],
  ['inline', 'esc-lt', 'Compare 1 \\< 2 and 3 > 2.', 'Compare 1 < 2 and 3 > 2.'],
  ['inline', 'star-math', 'Compute 5 * 3 * 2 now.', 'Compute 5 \\* 3 \\* 2 now.'],
  ['inline', 'snake-case', 'The snake_case_name stays.'],
  ['inline', 'underscore-edges', 'A lone _ and a lone * here.', 'A lone \\_ and a lone \\* here.'],
  ['inline', 'tilde-single', 'About ~5 minutes.', 'About \\~5 minutes.'],
  ['inline', 'ampersand', 'Fish & chips and R&D.'],
  ['inline', 'entity-nbsp', 'Keep&nbsp;together.'],
  ['inline', 'entity-lt', 'Write &lt;b&gt; as text.', 'Write \\<b> as text.'],
  ['inline', 'hard-break-spaces', 'Line one  \nLine two', 'Line one\\\nLine two'],
  ['inline', 'soft-break', 'Line one\nLine two\nLine three'],
  ['inline', 'tab-text', 'Col1\tCol2'],
  ['inline', 'rtl', 'مرحبا بالعالم and שלום'],
  ['inline', 'emoji-zwj', 'Family 👨‍👩‍👧 and flag 🇮🇹.'],
  ['inline', 'nfd-text', 'Café stays decomposed.'],
  ['inline', 'dollar-price', 'It costs $5 and then $6 more.'],
  ['inline', 'percent-single', 'Growth was 50% this year.'],
  ['inline', 'equals-compare', 'If a == b then stop.'],
  ['inline', 'hash-mid', 'Issue #123 and C# language.'],
  ['inline', 'exclaim-bracket', 'Wow! [not an image] ok.', 'Wow! \\[not an image\\] ok.'],
  ['inline', 'angle-text', 'A <not-a-tag and 1<2.'],
  ['inline', 'lt-escaped-tag', 'Write \\<b> literally.'],
  ['inline', 'lt-line-start', 'text\n\\<div>not html'],

  // ── block, more ────────────────────────────────────────────────────────────
  ['block', 'setext-h1', L('Title', '====='), '# Title'],
  ['block', 'setext-h2', L('Sub', '---'), '## Sub'],
  ['block', 'atx-closed', '## Closed ##', '## Closed'],
  ['block', 'heading-inline', '### A *styled* `heading` with [[Link]]'],
  ['block', 'heading-empty', '#'],
  ['block', 'seven-hashes', '####### not a heading'],
  ['block', 'hr-stars', L('a', '', '***', '', 'b'), L('a', '', '---', '', 'b')],
  ['block', 'hr-underscores', L('a', '', '___', '', 'b'), L('a', '', '---', '', 'b')],
  ['block', 'hr-spaced', L('a', '', '- - -', '', 'b'), L('a', '', '---', '', 'b')],
  ['block', 'quote-list', L('> Intro', '>', '> - one', '> - two')],
  ['block', 'quote-code', L('> ```js', '> let a = 1', '> ```')],
  ['block', 'quote-heading', L('> ## Quoted heading', '>', '> text')],
  ['block', 'quote-lazy', L('> lazy', 'continuation'), '> lazy\n> continuation'],
  ['block', 'quote-two-paras', L('> one', '>', '> two')],
  ['block', 'quote-triple', L('> a', '>', '> > b', '> >', '> > > c')],
  ['block', 'fence-tilde', L('~~~py', 'print(1)', '~~~'), L('```py', 'print(1)', '```')],
  ['block', 'fence-info', L('```js title="x.js"', 'a()', '```')],
  ['block', 'fence-blank-lines', L('```', 'a', '', '', 'b', '```')],
  ['block', 'fence-trailing-space', L('```', 'keep  ', '```')],
  ['block', 'fence-tabs', L('```', '\tindented', '```')],
  ['block', 'fence-contains-ticks', L('````', '```', 'inner', '```', '````')],
  ['block', 'fence-empty', L('```', '```')],
  ['block', 'fence-after-list', L('- item', '', '```', 'code', '```')],
  ['block', 'html-comment', '<!-- a note to self -->'],
  ['block', 'html-br', 'Before\n\n<br>\n\nAfter'],
  ['block', 'html-img', '<img src="a.png" width="200">'],
  ['block', 'html-table', L('<table>', '<tr><td>cell</td></tr>', '</table>')],
  ['block', 'html-two-blocks', L('<div>one</div>', '', '<div>two</div>')],
  ['block', 'html-around-md', L('Before **bold**', '', '<details>', '<summary>S</summary>', '</details>', '', 'After *it*')],
  ['block', 'footnotes-multi', L('One[^a] and two[^b].', '', '[^a]: First.', '[^b]: Second.')],
  ['block', 'footnote-continued', L('Text[^n].', '', '[^n]: First line', '    continued here')],
  ['block', 'refdefs-multi', L('[a][x] and [b][y]', '', '[x]: https://a.io', '[y]: https://b.io "B"'), L('[a](https://a.io) and [b](https://b.io "B")', '', '[x]: https://a.io', '', '[y]: https://b.io "B"')],
  ['block', 'paragraph-then-list', L('Intro', '- a', '- b'), L('Intro', '', '- a', '- b')],
  ['block', 'many-blank-lines', L('a', '', '', '', 'b'), L('a', '', 'b')],

  // ── lists, more ────────────────────────────────────────────────────────────
  ['list', 'bullets-star', L('* a', '* b'), L('- a', '- b')],
  ['list', 'lists-adjacent-bullets', L('- a', '', '* b', '', '+ c')],
  ['list', 'lists-adjacent-ordered', L('1. a', '', '1) b')],
  ['list', 'lists-adjacent-bullet-task', L('- a', '', '* [ ] b', '* [x] c')],
  ['list', 'bullets-plus', L('+ a', '+ b'), L('- a', '- b')],
  ['list', 'ordered-paren', L('1) a', '2) b'), L('1. a', '2. b')],
  ['list', 'ordered-all-ones', L('1. a', '1. b', '1. c'), L('1. a', '2. b', '3. c')],
  ['list', 'ordered-zero', L('0. a', '1. b')],
  ['list', 'ordered-wide', L('9. nine', '10. ten', '11. eleven')],
  ['list', 'ordered-nested-bullets', L('1. one', '   - a', '   - b', '2. two', '   - c')],
  ['list', 'bullets-nested-ordered', L('- one', '  1. a', '  2. b', '- two')],
  ['list', 'nested-three', L('- a', '  - b', '    - c', '      - d')],
  ['list', 'item-two-paras', L('- first', '', '  second', '', '- next')],
  ['list', 'item-quote', L('- item', '', '  > quoted', '', '- next')],
  ['list', 'item-empty', L('- a', '-', '- c')],
  ['list', 'item-multiline', L('- one', '  continues', '- two')],
  ['list', 'two-lists-comment', L('- a', '- b', '', '<!-- split -->', '', '- c')],
  ['list', 'list-after-heading', L('## Items', '', '- a', '- b')],
  ['list', 'tasks-upper-x', L('- [X] done'), '- [x] done'],
  ['list', 'tasks-nested-bullets', L('- [ ] parent', '  - plain child', '  - another')],
  ['list', 'tasks-inline-format', L('- [x] **bold** and [[Link]]', '- [ ] `code` item')],
  ['list', 'tasks-mixed-with-plain', L('- [ ] task', '- plain item'), L('- \\[ \\] task', '- plain item')],
  ['list', 'task-loose', L('- [ ] one', '', '- [x] two')],
  ['list', 'list-with-table', L('- item', '', '  | a | b |', '  | --- | --- |', '  | 1 | 2 |')],
  ['list', 'list-with-callout', L('- item', '', '  > [!note]', '  > inside')],

  // ── tables, more ───────────────────────────────────────────────────────────
  ['table', 'table-empty-cells', L('| a | b |', '| --- | --- |', '| | x |', '| y | |')],
  ['table', 'table-wikilink', L('| Note | Why |', '| --- | --- |', '| [[Alpha]] | the first |', '| [[Beta\\|b]] | second |')],
  ['table', 'table-code-pipe', L('| Code |', '| --- |', '| `a \\| b` |')],
  ['table', 'table-br', L('| A | B |', '| --- | --- |', '| line one<br>line two | x |')],
  ['table', 'table-one-col', L('| Only |', '| --- |', '| a |', '| b |')],
  ['table', 'table-header-only', L('| H1 | H2 |', '| --- | --- |')],
  ['table', 'table-after-para', L('Intro text', '', '| a | b |', '| --- | --- |', '| 1 | 2 |')],
  ['table', 'table-align-mixed', L('| a | b | c | d |', '| :--- | --- | ---: | :---: |', '| 1 | 2 | 3 | 4 |')],
  ['table', 'table-padded-input', L('| Name  | Qty |', '| ----- | --- |', '| Apple | 3   |'), L('| Name | Qty |', '| --- | --- |', '| Apple | 3 |')],
  ['table', 'table-math', L('| Formula |', '| --- |', '| $x^2$ |')],
  ['table', 'table-bold-link', L('| **Name** | [Docs](https://x.io) |', '| --- | --- |', '| a | b |')],
  ['table', 'table-two', L('| a |', '| --- |', '| 1 |', '', 'between', '', '| b |', '| --- |', '| 2 |')],

  // ── Obsidian-style extensions, more ───────────────────────────────────────
  ['ext', 'wikilink-heading-line', '## About [[Alpha]]'],
  ['ext', 'wikilink-bold', 'See **[[Alpha]]** now.'],
  ['ext', 'wikilink-italic-alias', 'Read *[[Alpha|the first]]* soon.'],
  ['ext', 'wikilink-quote', '> Quote with [[Alpha]]'],
  ['ext', 'wikilink-adjacent', '[[A]][[B]] and [[C]], [[D]].'],
  ['ext', 'wikilink-underscore', 'Open [[snake_case_note]] and [[star*note]].'],
  ['ext', 'wikilink-unicode', 'Visit [[Caffè e città]] and [[日本語のノート]].'],
  ['ext', 'wikilink-spaces', 'A [[  Padded name  ]] link.'],
  ['ext', 'wikilink-pipe-pipe', 'Odd [[a|b|c]] alias.'],
  ['ext', 'wikilink-empty', 'Empty [[]] brackets.', 'Empty \\[\\[\\]\\] brackets.'],
  ['ext', 'wikilink-unclosed', 'Open [[ without close.', 'Open \\[\\[ without close.'],
  ['ext', 'wikilink-multiline', 'Not [[a\nlink]] here.', 'Not \\[\\[a\nlink\\]\\] here.'],
  ['ext', 'embed-pdf', '![[Report.pdf#page=3]]'],
  ['ext', 'embed-size', '![[photo.png|100x200]]'],
  ['ext', 'embed-inline', 'Text ![[note]] more text.'],
  ['ext', 'highlight-bold', 'A **==both==** here and ==*slanted*==.', 'A **==both==** here and *==slanted==*.'],
  ['ext', 'highlight-several', '==one== and ==two== and ==three==.'],
  ['ext', 'highlight-lonely', 'Just == here.'],
  ['ext', 'math-inline-braces', 'Take $\\frac{a}{b}$ and $x_{i}^{2}$.'],
  ['ext', 'math-inline-two', 'Both $a$ and $b$ hold.'],
  ['ext', 'math-block-multiline', L('$$', 'a = b', 'c = d', '$$')],
  ['ext', 'math-block-between', L('Before', '', '$$', 'x', '$$', '', 'After')],
  ['ext', 'math-dollar-pair-spaced', 'Costs $ 5 and $ 6.', 'Costs \\$ 5 and \\$ 6.'],
  ['ext', 'callout-upper', L('> [!NOTE] Loud', '> body')],
  ['ext', 'callout-list', L('> [!todo] Do this', '> - one', '> - two')],
  ['ext', 'callout-code', L('> [!example]', '> ```js', '> a()', '> ```')],
  ['ext', 'callout-nested-quote', L('> [!quote]', '> > deep', '>', '> text')],
  ['ext', 'callout-open-fold', L('> [!faq]+ Open by default', '> Answer.')],
  ['ext', 'callout-bad-kind', L('> [! not a callout]', '> text'), L('> \\[! not a callout\\]', '> text')],
  ['ext', 'comment-in-list', L('- a %%private%% b', '- c')],
  ['ext', 'comment-spaces', 'Here %% spaced comment %% there.'],
  ['ext', 'comment-unclosed', 'Lone %% marks.'],
  ['ext', 'comment-escaped-pair', 'Literal \\%\\%not a comment\\%\\% text.'],
  ['ext', 'callout-empty-body', '> [!note]'],
  ['ext', 'tags-several', 'Tags: #a #b/c #d-e_f and #2026.'],
  ['ext', 'tag-start-of-line', '\\#not-a-heading-just-a-tag', '#not-a-heading-just-a-tag'],
  ['ext', 'underline', 'Some <u>underlined</u> text.'],
  ['ext', 'kbd-in-list', L('- Press <kbd>Esc</kbd>', '- Then <kbd>Enter</kbd>')],
  ['ext', 'inline-comment-html', 'Text <!-- hidden --> more.'],
  ['ext', 'footnote-in-text', 'Claim[^1], and another[^long-id].'],

  // ── document level ─────────────────────────────────────────────────────────
  ['doc', 'fm-empty', L('---', '---', '', 'Body.')],
  ['doc', 'fm-only', L('---', 'a: 1', '---'), L('---', 'a: 1', '---')],
  ['doc', 'fm-no-blank', L('---', 'a: 1', '---', '# T', '', 'x'), L('---', 'a: 1', '---', '', '# T', '', 'x')],
  ['doc', 'fm-two-blank', L('---', 'a: 1', '---', '', '', 'x'), L('---', 'a: 1', '---', '', 'x')],
  ['doc', 'fm-trailing-space-fence', L('---', 'a: 1', '--- ', '', 'x')],
  ['doc', 'fm-dashes-in-value', L('---', 'title: "a --- b"', 'note: x', '---', '', 'y')],
  ['doc', 'fm-then-hr', L('---', 'a: 1', '---', '', '---', '', 'x')],
  ['doc', 'fm-multiline-block', L('---', 'desc: |', '  first', '  second', 'tags:', '  - a', '  - b', '---', '', 'x')],
  ['doc', 'fm-unicode', L('---', 'title: Caffè ☕', '---', '', 'x')],
  ['doc', 'hr-first-no-fm', L('---', '', 'text'), L('---', '', 'text')],
  ['doc', 'whitespace-only', '   \n\n  ', ''],
  ['doc', 'newlines-only', '\n\n\n', ''],
  ['doc', 'crlf', 'Line one\r\n\r\nLine two\r\n', 'Line one\n\nLine two'],
  ['doc', 'crlf-fm', '---\r\na: 1\r\n---\r\n\r\nBody\r\n', '---\r\na: 1\r\n---\n\nBody'],
  ['doc', 'bom', '﻿# Title', '# Title'],
  ['doc', 'leading-blank-lines', '\n\n# Title', '# Title'],
  ['doc', 'trailing-blank-lines', '# Title\n\n\n\n', '# Title'],
  ['doc', 'trailing-spaces-line', 'text   \n\nnext', 'text\n\nnext'],
  ['doc', 'very-long-line', 'word '.repeat(2000).trim()],
  ['doc', 'unicode-heavy', L('# Заголовок', '', 'Ελληνικά, 中文, हिन्दी, العربية, 한국어, 🧪.')],
  ['doc', 'deep-mix', L('# Title', '', '> [!note] Mixed', '> - [ ] task with [[Link]]', '>   and ==mark==', '', '| a | b |', '| --- | --- |', '| `c` | $d$ |', '', '```js', 'x()', '```')],
] as const;
