#!/usr/bin/env bash
# Noted release — local build, sign, notarize, and verify the staple.
#
# Apple credentials (APPLE_ID / APPLE_TEAM_ID / APPLE_APP_SPECIFIC_PASSWORD) are
# read from .env.local (gitignored) so they never touch the repo or CI. Point at
# a different file with APPLE_CREDS_ENV=/path/to/creds.env.
#
# Usage:
#   bash scripts/release.sh                  # full build + sign + notarize + staple
#   bash scripts/release.sh --notarize-only  # skip the build; re-notarize the DMGs
#                                            # already in release/ (e.g. a creds retry)
set -euo pipefail
cd "$(dirname "$0")/.."

NOTARIZE_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --notarize-only) NOTARIZE_ONLY=1 ;;
    *) echo "✗ unknown argument: $arg" >&2; exit 2 ;;
  esac
done

# ── Load credentials ──────────────────────────────────────────────────────
CREDS="${APPLE_CREDS_ENV:-.env.local}"
if [[ -f "$CREDS" ]]; then
  echo "→ Loading Apple credentials from $CREDS"
  set -a
  # shellcheck disable=SC1090
  source "$CREDS"
  set +a
else
  echo "→ No $CREDS found; relying on the environment"
fi

for v in APPLE_ID APPLE_TEAM_ID APPLE_APP_SPECIFIC_PASSWORD; do
  if [[ -z "${!v:-}" ]]; then
    echo "✗ Missing $v — set it in .env.local (copy from .env.local.example) or the environment." >&2
    exit 1
  fi
done
echo "✓ Apple credentials present (APPLE_ID=$APPLE_ID, TEAM=$APPLE_TEAM_ID)"

# ── Build + sign (electron-builder signs with the Developer ID + hardened runtime) ──
if [[ "$NOTARIZE_ONLY" == 1 ]]; then
  echo "→ --notarize-only: skipping the build, using existing release/*.dmg"
else
  npm run build
fi

VERSION="$(node -p "require('./package.json').version")"

# ── Notarize + staple each DMG ────────────────────────────────────────────
# electron-builder signs the .app but does not notarize the DMG file itself, so
# submit each DMG to Apple and staple the ticket — otherwise the downloaded DMG
# fails offline Gatekeeper validation. Scoped to this build's version so old
# artifacts in release/ aren't re-submitted.
echo
echo "── Notarizing + stapling DMGs (v$VERSION) ──"
shopt -s nullglob
found=0
for dmg in "release/Noted-$VERSION"*.dmg; do
  found=1
  echo "== $dmg =="
  xcrun notarytool submit "$dmg" \
    --apple-id "$APPLE_ID" --team-id "$APPLE_TEAM_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD" \
    --wait
  xcrun stapler staple "$dmg" && echo "  ✓ stapled" || { echo "  ✗ staple failed" >&2; exit 1; }
done
[[ "$found" == 1 ]] || { echo "✗ no release/Noted-$VERSION*.dmg found" >&2; exit 1; }
echo "Done — v$VERSION DMGs signed, notarized, stapled."

# ── Rebuild the update metadata from the STAPLED DMGs ──────────────────────
# Stapling rewrites each DMG (it appends the notarization ticket), so the
# sha512/size electron-builder recorded in latest-mac.yml at build time — before
# stapling — no longer match the files we are about to ship. Left as-is, every
# macOS auto-update would download the DMG, hit a hash mismatch, and silently
# refuse to update. Regenerate the yml from the final bytes; drop the .blockmap
# files for the same reason (a stale blockmap only forces a fallback to full
# download, so shipping none is cleaner than shipping wrong ones).
YML="release/latest-mac.yml"
if [[ ! -f "$YML" ]]; then
  echo "✗ $YML is missing — auto-update needs it." >&2
  echo "  It is generated by 'npm run build' (needs build.publish set). Run a full build," >&2
  echo "  not --notarize-only, at least once for this version." >&2
  exit 1
fi
echo
echo "── Rebuilding $YML from the stapled DMGs ──"
sha_b64() { openssl dgst -sha512 -binary "$1" | openssl base64 -A; }
# Preserve electron-builder's file order and its choice of `path` (the primary
# artifact); only the hashes, sizes, and date change.
path_file="$(awk '/^path:/{print $2; exit}' "$YML")"
# while-read (not mapfile) so this runs on the bash 3.2 macOS ships.
urls=()
while IFS= read -r u; do urls+=("$u"); done < <(awk '/^  - url:/{print $3}' "$YML")
release_date="$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"
{
  echo "version: $VERSION"
  echo "files:"
  for u in "${urls[@]}"; do
    f="release/$u"
    [[ -f "$f" ]] || { echo "✗ $f referenced by yml is missing" >&2; exit 1; }
    echo "  - url: $u"
    echo "    sha512: $(sha_b64 "$f")"
    echo "    size: $(stat -f%z "$f")"
  done
  echo "path: $path_file"
  echo "sha512: $(sha_b64 "release/$path_file")"
  echo "releaseDate: '$release_date'"
} > "$YML.tmp" && mv "$YML.tmp" "$YML"
echo "  ✓ regenerated with post-staple hashes"

# Verify every hash/size in the yml matches the file on disk before we call it done.
node - "$YML" <<'NODE'
const fs = require('fs'), crypto = require('crypto');
const yml = fs.readFileSync(process.argv[2], 'utf8');
const entries = [...yml.matchAll(/- url: (.+)\n\s+sha512: (.+)\n\s+size: (\d+)/g)];
let bad = 0;
for (const [, url, sha, size] of entries) {
  const buf = fs.readFileSync('release/' + url.trim());
  const got = crypto.createHash('sha512').update(buf).digest('base64');
  const ok = got === sha.trim() && String(buf.length) === size.trim();
  console.log(`  ${ok ? 'OK ' : 'BAD'} ${url.trim()}`);
  if (!ok) bad++;
}
process.exit(bad ? 1 : 0);
NODE

# Stale, pre-staple blockmaps: remove so nothing ships that no longer matches.
rm -f "release/Noted-$VERSION"*.dmg.blockmap
echo "  ✓ removed stale .dmg.blockmap files"

# ── Publish checklist ─────────────────────────────────────────────────────
echo
echo "── Upload these assets to the GitHub release ──"
ASSETS=("$YML")
for f in "release/Noted-$VERSION"*.dmg; do ASSETS+=("$f"); done
printf '  %s\n' "${ASSETS[@]}"
echo
echo "  gh release create v$VERSION ${ASSETS[*]} \\"
echo "    --title 'Noted $VERSION' --notes-file <notes.md>"
echo
echo "  (add --draft first if you want to eyeball it before it goes public)"
echo "  Note: if the vX.Y.Z tag already triggered the CI draft with the Windows/"
echo "  Linux artifacts, upload into it instead: gh release upload v$VERSION ${ASSETS[*]}"
